<a href="https://colab.research.google.com/github/milleau98/2026-gig-data-analysis/blob/main/analyses/correlation_analyses.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# stock price
stock_df_annually = pd.read_csv('../data/yfinance/gig_data_annually.csv', parse_dates=['Date'])
stock_df_quarterly = pd.read_csv('../data/yfinance/gig_data_quarterly.csv', parse_dates=['Date'])
stock_df_monthly = pd.read_csv('../data/yfinance/gig_data_monthly.csv', parse_dates=['Date'])

# google trend data
google_df_annually = pd.read_csv('../data/google_trends/google_trends_annual.csv', parse_dates=['date'])
google_df_quarterly = pd.read_csv('../data/google_trends/google_trends_quarterly.csv', parse_dates=['date'])
google_df_monthly = pd.read_csv('../data/google_trends/google_trends_monthly.csv', parse_dates=['date'])

# FRED data
fred_df_annually = pd.read_csv('../data/fred/fred_annual_data.csv', parse_dates=['date'])
fred_df_quarterly = pd.read_csv('../data/fred/fred_quarterly_data.csv', parse_dates=['date'])
fred_df_monthly = pd.read_csv('../data/fred/fred_monthly_data.csv', parse_dates=['date'])

In [ ]:
google_df_annually_long = google_df_annually.melt(
    id_vars=['year'],
    value_vars= ['Uber','Lyft','DoorDash','Instacart','Grubhub','Fiverr','Upwork','side hustle','gig','Herbalife','Primerica','Tupperware','Avon','Etsy', 'Shopify', 'Udemy'],
    var_name = 'company',
    value_name = 'SearchInterest'
)

google_df_quarterly_long = google_df_quarterly.melt(
    id_vars=['year', 'quarter'],
    value_vars= ['Uber','Lyft','DoorDash','Instacart','Grubhub','Fiverr','Upwork','side hustle','gig','Herbalife','Primerica','Tupperware','Avon','Etsy', 'Shopify', 'Udemy'],
    var_name = 'company',
    value_name = 'SearchInterest'
)

google_df_monthly_long = google_df_monthly.melt(
    id_vars=['year', 'month'],
    value_vars= ['Uber','Lyft','DoorDash','Instacart','Grubhub','Fiverr','Upwork','side hustle','gig','Herbalife','Primerica','Tupperware','Avon','Etsy', 'Shopify', 'Udemy'],
    var_name = 'company',
    value_name = 'SearchInterest'
)

In [ ]:
# rename columns to match across datasets
stock_df_annually = stock_df_annually.rename(columns={'Year': 'year'})
stock_df_quarterly = stock_df_quarterly.rename(columns={'Year': 'year'})
stock_df_monthly = stock_df_monthly.rename(columns={'Year': 'year'})

stock_df_quarterly = stock_df_quarterly.rename(columns={'Quarter': 'quarter'})
stock_df_monthly = stock_df_monthly.rename(columns={'Month': 'month'})

merged_df_annually = stock_df_annually.merge(google_df_annually_long, on='year', how='left').merge(fred_df_annually, on='year', how='left')
merged_df_quarterly = stock_df_quarterly.merge(google_df_quarterly_long, on=['year', 'quarter'], how='left').merge(fred_df_quarterly, on=['year', 'quarter'], how='left')
merged_df_monthly = stock_df_monthly.merge(google_df_monthly_long, on=['year', 'month'], how='left').merge(fred_df_monthly, on=['year', 'month'], how='left')

merged_df_annually.head()

,Date,year,Company,Ticker,industryKey,sectorKey,Close,Volume,Close_lag1,Volume_lag1,...,gdp_data_quarterly,gdp_data_lag_quarterly,gdp_real_data_quarterly,gdp_real_data_lag_quarterly,cpi_inflation_data_annual,cpi_inflation_data_lag_annual,median_income_real_data_annual,median_income_real_data_lag_annual,median_income_data_annual,median_income_data_lag_annual
0,2018-12-31,2018,Upwork,UPWK,internet-content-information,communication-services,18.110001,337200.0,NaN,NaN,...,20656.5155,20436.32075,20193.89525,20088.26475,2.442583,2.13011,77700.0,76710.0,63180.0,61140.0
1,2018-12-31,2018,Upwork,UPWK,internet-content-information,communication-services,18.110001,337200.0,NaN,NaN,...,20656.5155,20436.32075,20193.89525,20088.26475,2.442583,2.13011,77700.0,76710.0,63180.0,61140.0
2,2018-12-31,2018,Upwork,UPWK,internet-content-information,communication-services,18.110001,337200.0,NaN,NaN,...,20656.5155,20436.32075,20193.89525,20088.26475,2.442583,2.13011,77700.0,76710.0,63180.0,61140.0
3,2018-12-31,2018,Upwork,UPWK,internet-content-information,communication-services,18.110001,337200.0,NaN,NaN,...,20656.5155,20436.32075,20193.89525,20088.26475,2.442583,2.13011,77700.0,76710.0,63180.0,61140.0
4,2018-12-31,2018,Upwork,UPWK,internet-content-information,communication-services,18.110001,337200.0,NaN,NaN,...,20656.5155,20436.32075,20193.89525,20088.26475,2.442583,2.13011,77700.0,76710.0,63180.0,61140.0

In [ ]:
annual_cols_to_keep = ['year', 'company', 'Close', 'Volume', 'Close_lag1', 'Volume_lag1', 'cpi_inflation_data_annual', 'unemployment_data_monthly', 'SearchInterest']

cleaned_df_annually = merged_df_annually[annual_cols_to_keep].copy()

cleaned_df_annually.head()

,year,company,Close,Volume,Close_lag1,Volume_lag1,cpi_inflation_data_annual,unemployment_data_monthly,SearchInterest
0,2018,Uber,18.110001,337200.0,NaN,NaN,2.442583,3.891667,77.583333
1,2018,Lyft,18.110001,337200.0,NaN,NaN,2.442583,3.891667,21.916667
2,2018,DoorDash,18.110001,337200.0,NaN,NaN,2.442583,3.891667,10.666667
3,2018,Instacart,18.110001,337200.0,NaN,NaN,2.442583,3.891667,5.500000
4,2018,Grubhub,18.110001,337200.0,NaN,NaN,2.442583,3.891667,13.666667

In [ ]:
quarterly_cols_to_keep = ['year','quarter', 'company', 'Close', 'Volume', 'Close_lag1', 'Volume_lag1', 'cpi_inflation_data_annual', 'unemployment_data_monthly', 'SearchInterest']

cleaned_df_quarterly = merged_df_quarterly[quarterly_cols_to_keep].copy()

cleaned_df_quarterly.head()

,year,quarter,company,Close,Volume,Close_lag1,Volume_lag1,cpi_inflation_data_annual,unemployment_data_monthly,SearchInterest
0,2018,4,Uber,18.110001,337200.0,NaN,NaN,2.442583,3.833333,72.666667
1,2018,4,Lyft,18.110001,337200.0,NaN,NaN,2.442583,3.833333,21.333333
2,2018,4,DoorDash,18.110001,337200.0,NaN,NaN,2.442583,3.833333,15.333333
3,2018,4,Instacart,18.110001,337200.0,NaN,NaN,2.442583,3.833333,6.000000
4,2018,4,Grubhub,18.110001,337200.0,NaN,NaN,2.442583,3.833333,17.000000

In [ ]:
monthly_cols_to_keep = ['year','month', 'company', 'Close', 'Volume', 'Close_lag1', 'Volume_lag1', 'cpi_inflation_data_annual', 'unemployment_data_monthly', 'SearchInterest']

cleaned_df_monthly = merged_df_monthly[monthly_cols_to_keep].copy()

cleaned_df_monthly.head()

,year,month,company,Close,Volume,Close_lag1,Volume_lag1,cpi_inflation_data_annual,unemployment_data_monthly,SearchInterest
0,2018,10,Uber,19.200001,337600.0,NaN,NaN,2.442583,3.8,75.0
1,2018,10,Lyft,19.200001,337600.0,NaN,NaN,2.442583,3.8,22.0
2,2018,10,DoorDash,19.200001,337600.0,NaN,NaN,2.442583,3.8,14.0
3,2018,10,Instacart,19.200001,337600.0,NaN,NaN,2.442583,3.8,6.0
4,2018,10,Grubhub,19.200001,337600.0,NaN,NaN,2.442583,3.8,17.0